### ISSUE TITLE
Not cleaning restore last session

### ISSUE THREAD

**Issue by oldchap32** [gpiskas/CleanQuit#1]
Using Firefox 28.0 on mac os X, the latest version of CleanQuit doesn't clear the content of my last browsing session. After relaunching Firefox, i can still use the "restore last session" to get the web page i was visiting.

Any way to get it cleaned aswell ?

Thanks.

**Comment by gpiskas** [comment]
Hi, You mean that the last tabs are still there when you relaunch?

**Comment by oldchap32** [comment]
nope, they're not directly viewable nor present in the history but i just have to use the "restore previous session" command from the history dropdown menu to have them back.

that way anyone using the computer right after me would be able to see all tabs i had open even if i used cleanquit to clean up.

please find the screen capture of the history menu with "restore previous session" (sorry it's the french version but you should find it there)

it would be great if Cleanquit would prevent this aswell.

----- Mail original -----
De: "George Piskas" notifications@github.com
À: "Geo-Piskas/CleanQuit" CleanQuit@noreply.github.com
Cc: "oldchap32" oldchap.truc@free.fr
Envoyé: Jeudi 17 Avril 2014 20:42:17
Objet: Re: [CleanQuit] Not cleaning restore last session (#1)

Hi, You mean that the last tabs are still there when you relaunch?

**Comment by gpiskas** [comment]
Please check out the newest firefox version and the latest addon version. For optimal results, do a fresh installation of both.
