### ISSUE TITLE
Quits but does not clean

### ISSUE THREAD

**Issue by grrrrr** [gpiskas/CleanQuit#10]
With latest versions of Firefox for Android `CleanQuit` no longer works.   All options for cleaning are checked in the preferences

**What happens**
Select CleanQuit from the firefox menu.  The browser quits,  on restart browser history and other usage are still available

**What should happen**

Select CleanQuit from the firefox menu.  The browser quits,  on restart browser all previous usage history has been wiped

**Other details**

* OS: Android 6.0.1
* Browser: Firefox 49.0.2
* CleanQuit: 1.5.1

**Comment by rdimmitt** [comment]
Same issue.

Android 7
Firefox 52
Cleanquit 1.5.1

**Comment by grrrrr** [comment]
@rdimmitt I got this working

- go to firefox: settings -> Clear Private Data
- uncheck everything
- navigate away from the settings page
- go back to Clear private data 
- check everything
- click clear data
- Clean Quit should now work

**Comment by rdimmitt** [comment]
Fixed. Working now. Thanks!!!
