### ISSUE TITLE
Cookie safe list

### ISSUE THREAD

**Issue by Soboku** [gpiskas/CleanQuit#2]
Using cleanquit with Firefox Beta for Android on my Nexus 5 love everything about it but one. Is it possible to add a safe list for Cookies so that when clean is set to delete cookies on exit it will only delete the ones that are not in the safe list? I have to have cookies enabled and saved for lastpass plugin to remember my password for last pass. I no it defeats the purpose if I tell lastpass to remember but the password is just to long to remember.

**Comment by gpiskas** [comment]
Well yea this come in contrast to the actual purpose of the addon. Moreover, the safest way to go for your personal security is to memorize your lastpass password, no matter how long or complicated it may be. However, your suggestion has been noted. Thanks!
