### ISSUE TITLE
about:downloads not cleared

### ISSUE THREAD

**Issue by CarlDuisberg** [gpiskas/CleanQuit#3]
After using cleanquit I still find my last 30 day history of downloads under about:downloads.

**Comment by gpiskas** [comment]
Which platform are you using? This is strange, since I just tested this and it works perfectly. Are you sure you have checked the delete downloads option?

**Comment by gpiskas** [comment]
Downloads cannot be cleared since version 1.5 and after, for firefox 31+. This happens because they have been separated from firefox, as system files.
