### ISSUE TITLE
won't install button on desktop version

### ISSUE THREAD

**Issue by notafrog** [gpiskas/CleanQuit#4]
the Android version works on my phone so I installed (and supported financially) the desktop version.  However, there is no button installed that I can find on my browser.  CLeanquit does show up in my add-ons, but no other evidence of its being installed shows up anywhere,

**Comment by gpiskas** [comment]
Make sure it is enabled and you will find the icon in "Customize Toolbar" dialogue window.

**Comment by notafrog** [comment]
found it!  Wow...you are fast!  Thanks Much.  Hope people are supporting your work.  I am a firm believer that we should pay for what we benefit from.  :-)

**Comment by gpiskas** [comment]
You're welcome! Thanks for your kind words and your support!
