### ISSUE TITLE
Toolbar icon not available

### ISSUE THREAD

**Issue by htdavis** [gpiskas/CleanQuit#5]
XPI installs successfully in FF 29, but the icon is missing and is not available to be added manually.

**Comment by gpiskas** [comment]
Choose Customize from the menu.

**Comment by htdavis** [comment]
Did you really think I would've posted if it were that easy? =)
![no_button](https://cloud.githubusercontent.com/assets/6385081/3039817/0238be48-e0e4-11e3-9280-a69ea8df6b75.png)

**Comment by gpiskas** [comment]
Hmm, this is strange! I can see it there. Well, I guess I will have to update it to firefox 29 UI.
