### ISSUE TITLE
Android: Confirmation on back button

### ISSUE THREAD

**Issue by Jamesgresley** [gpiskas/CleanQuit#6]
i would appreciate a confirmation on back button press added.  i keep exiting by accident and forgetfulness by using the back button.  i have seen scripts to fix this but i do not know how to add them myself. i would love seeing this feature added to your extention. 

thanks much
James Gresley

**Comment by gpiskas** [comment]
The back button is a differend and non-linked functionality to cleanquit! Back button just suspends Firefox and puts it in the background while CleanQuit quits it!

**Comment by Jamesgresley** [comment]
I realize that it is not linked,  that is the problem as by habit and
accident, I find myself more often using the back button to exit.

Thank you
James Gresley

**Comment by gpiskas** [comment]
Well to tell you the truth, I did something like what you suggest in a previous test version and users did not seem to like it.

Cheers,
George

**Comment by Jamesgresley** [comment]
Could you offer it as a choice with a tick box to turn on and off Maybe?
