### ISSUE TITLE
Still not available...did i miss something?

### ISSUE THREAD

**Issue by htdavis** [gpiskas/CleanQuit#7]
![no_button](https://cloud.githubusercontent.com/assets/6385081/3039839/793c854c-e0e4-11e3-8465-9b311ababbca.png)

**Comment by htdavis** [comment]
Interesting development.
I just switched to a new computer and finished installing the extension. The button now appears in the toolbar without any changes!
Using FF 29.0.1

**Comment by gpiskas** [comment]
Cool!
