### ISSUE TITLE
Firefox v31 (Android) doesn't quit

### ISSUE THREAD

**Issue by RichardRobertson** [gpiskas/CleanQuit#8]
I've been using this addon for my Android and it's worked great until today when v31 downloaded. It gives the cleaning up message and does delete the selected histories, but Firefox isn't closing like it used to. It just sits on the new tab page after all tabs close.

**Comment by logic** [comment]
Seeing the same thing here on the Firefox 31 beta.

**Comment by gpiskas** [comment]
Thanks. Working on it.

**Comment by gpiskas** [comment]
Waiting for the update (v1.5) to go live on firefox addons!

**Comment by RichardRobertson** [comment]
Confirmed working.
